// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("samsa")
	ScopeName = "github.com/kmuto/opentelemetry-collector-components-kmuto/receiver/samsareceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
